CREATE TABLE IF NOT EXISTS `users` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`username` VARCHAR(50) NOT NULL UNIQUE,
	`email` VARCHAR(320) NOT NULL UNIQUE,
	`pass_hash` CHAR(60) NOT NULL,
	`role` ENUM('admin', 'user') NOT NULL DEFAULT 'user',
	`active` BOOLEAN NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT NOW(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
	PRIMARY KEY(`id`)
);
